// createStructure.js
const fs = require("fs");
const path = require("path");

const structure = [
  "public/index.html",
  "public/favicon.ico",
  "src/assets/images/",
  "src/assets/styles/globals.css",
  "src/components/common/Button.jsx",
  "src/components/common/Input.jsx",
  "src/components/common/Select.jsx",
  "src/components/common/Modal.jsx",
  "src/components/common/Table.jsx",
  "src/components/common/Card.jsx",
  "src/components/common/Badge.jsx",
  "src/components/common/Pagination.jsx",
  "src/components/common/SearchBar.jsx",
  "src/components/common/DatePicker.jsx",
  "src/components/common/FileUpload.jsx",
  "src/components/common/Loader.jsx",
  "src/components/layout/Sidebar.jsx",
  "src/components/layout/Header.jsx",
  "src/components/layout/Footer.jsx",
  "src/components/layout/Layout.jsx",
  "src/components/dashboard/DashboardStats.jsx",
  "src/components/dashboard/SalesChart.jsx",
  "src/components/dashboard/RecentOrders.jsx",
  "src/components/dashboard/LowStockAlert.jsx",
  "src/components/dashboard/KittyLeaderboard.jsx",
  "src/components/products/ProductList.jsx",
  "src/components/products/ProductForm.jsx",
  "src/components/products/ProductCard.jsx",
  "src/components/products/ProductImport.jsx",
  "src/components/products/StockManagement.jsx",
  "src/components/products/ProductFilters.jsx",
  "src/components/customers/CustomerList.jsx",
  "src/components/customers/CustomerForm.jsx",
  "src/components/customers/CustomerCard.jsx",
  "src/components/customers/CustomerMerge.jsx",
  "src/components/employees/EmployeeList.jsx",
  "src/components/employees/EmployeeForm.jsx",
  "src/components/employees/RoleManagement.jsx",
  "src/components/employees/PermissionMatrix.jsx",
  "src/components/employees/DiscountLimits.jsx",
  "src/components/sales/SalesList.jsx",
  "src/components/sales/SaleForm.jsx",
  "src/components/sales/DraftSale.jsx",
  "src/components/sales/ProformaInvoice.jsx",
  "src/components/sales/InvoiceGenerator.jsx",
  "src/components/sales/PaymentForm.jsx",
  "src/components/sales/SalesLog.jsx",
  "src/components/sales/InvoicePDF.jsx",
  "src/components/delivery/DeliveryBoard.jsx",
  "src/components/delivery/DeliveryCard.jsx",
  "src/components/delivery/DeliveryAssignment.jsx",
  "src/components/delivery/DeliveryTracking.jsx",
  "src/components/delivery/OTPVerification.jsx",
  "src/components/delivery/DeliveryTimeline.jsx",
  "src/components/reports/SalesReport.jsx",
  "src/components/reports/StockReport.jsx",
  "src/components/reports/KittyReport.jsx",
  "src/components/reports/GSTReport.jsx",
  "src/components/reports/PaymentReport.jsx",
  "src/pages/Dashboard.jsx",
  "src/pages/Products.jsx",
  "src/pages/Customers.jsx",
  "src/pages/Employees.jsx",
  "src/pages/Sales.jsx",
  "src/pages/Delivery.jsx",
  "src/pages/Reports.jsx",
  "src/pages/Settings.jsx",
  "src/pages/Login.jsx",
  "src/services/api.js",
  "src/services/authService.js",
  "src/services/productService.js",
  "src/services/customerService.js",
  "src/services/employeeService.js",
  "src/services/salesService.js",
  "src/services/deliveryService.js",
  "src/services/reportService.js",
  "src/context/AuthContext.jsx",
  "src/context/ThemeContext.jsx",
  "src/context/NotificationContext.jsx",
  "src/hooks/useAuth.js",
  "src/hooks/useApi.js",
  "src/hooks/useDebounce.js",
  "src/hooks/usePagination.js",
  "src/hooks/usePermissions.js",
  "src/utils/validators.js",
  "src/utils/formatters.js",
  "src/utils/constants.js",
  "src/utils/helpers.js",
  "src/utils/permissions.js",
  "src/routes/AppRoutes.jsx",
  "src/routes/PrivateRoute.jsx",
  "src/routes/PublicRoute.jsx",
  ".env",".gitignore","package.json","tailwind.config.js","README.md"
];

structure.forEach((file) => {
  const dir = path.dirname(file);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  if (!fs.existsSync(file)) fs.writeFileSync(file, "");
});

//console.log("✅ Project structure created successfully!");
